proxy:
  image: vshevchenko/proxy:1.0
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=192.168.1.189
    - NGINX_PROXY=http://identidock:9090
  log_driver: syslog

identidock:
  image: vshevchenko/identidock:newest
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD
  log_driver: syslog

dnmonster:
  image: amouat/dnmonster

redis:
  image: redis

logstash:
  image: logstash:1.5
  volumes:
    - ./logstash.conf:/etc/logstash.conf
  links:
    - elasticsearch
  ports:
    - "5544:5544"
  command:  -f /etc/logstash.conf
  log_driver: journald

elasticsearch:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9100:9100"
  log_driver: journald

kibana:
  image: kibana:4.0
  environment:
    ELASTICSEARCH_URL: http://elasticsearch:9200
  links:
    - elasticsearch
  ports:
    - "5601:5601"
  log_driver: journald
